vagrantfile:
    vm:
        hostname: am.araneum.dev
        memory: 2048
        cpus: 1
        network:
            private_network: 192.168.50.100
            public_network: 192.168.70.2
        synced_folder:
            araneum.dev:
                source: ./www
                target: /var/www
nginx:
    vhosts:
        core.araneum.dev:
            server_name: core.am.araneum.dev
            server_aliases:
                - www.core.am.araneum.dev
        aggregator.araneum.dev:
            server_name: aggregator.am.araneum.dev
            server_aliases:
                - www.aggregator.am.araneum.dev
        cluster.araneum.dev:
            server_name: cluster.am.araneum.dev
            server_aliases:
                - www.cluster.am.araneum.dev
